name: Deploy Vite Site to Pages

on:
  push:
    branches: ["main"] # Change to "master" if your default branch is master

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: './artifacts/syspro-technologies/package.json' 

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        working-directory: './artifacts/syspro-technologies'

      - name: Build site
        env:
          BASE_PATH: './'
          PORT: 3000
        run: |
          pnpm run build
          echo "sysprotechnologies.org" > ./dist/public/CNAME
        working-directory: './artifacts/syspro-technologies'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './artifacts/syspro-technologies/dist/public' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
